apiVersion: v1
kind: Service
metadata:
  name: wheathers
  labels:
    run: wheathers
spec:
  type: NodePort
  ports:
  - nodePort: 30800 # outter port
    port: 8080      # service port
    targetPort: 8000 # container port (pod port)
    protocol: TCP
    name: http
  selector:
    app: wheathers
  type: LoadBalancer
  externalIPs:
  - 52.220.34.136